id: "cellar-crawl"
title: "Cellar Crawl"
description: "Explore the dark cellar beneith a creepy house to discover its secret."
head:
  - "shared/analytics/header/analytics.html"
deps:
  - "games/cellar-crawl"
  - "shared/analytics/js"
