id: "journey"
title: "Journey"
description: "Travel the high seas, overcoming challenges in an Oregon Trail inspired game."
head:
  - "shared/analytics/header/analytics.html"
deps:
  - "games/journey"
  - "shared/analytics/js"
