name: Deploy Stories

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Setup Tweego
        run: go install github.com/tmedwards/tweego

      - name: Build Stories
        run: |
          go get gopkg.in/yaml.v2
          go run builder/*

      - name: Prepare Deploy Package
        run: |
          mkdir dist
          cp genfiles/public/* dist
          cp genfiles/games/* dist
          cp CNAME dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
