name: Deploy

on:
  push:
    branches:
      - gh-actions

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Setup Tweego
        run: |
          go get github.com/tmedwards/tweego
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Build Stories
        run: |
          mkdir dist
          ./build.sh journey
          ./build.sh cellar-crawl

      - name: Prepare Deploy Package
        run: cp public/* dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.